### ISSUE TITLE
Wicked-Charts Chartjs integration

### ISSUE THREAD

**Issue by maximAtanasov** [chartjs/www.chartjs.org#3]
Hello,

You may have heard of the Java library Wicked-Charts.
It allows users to configure and use their charts in Java using the Wicket framework.
The library used to only support Highcharts, but due to the licencing model of that library, we have decided to build a wrapper around Chartjs as well. 

The latest version of the library (3.1.0) supports Chartjs and Wicket 8.
Here is a link to the repo: https://github.com/adessoAG/wicked-charts
and a link to our Showcase app: https://wicked-charts-showcase.appspot.com

It would be great if you had a look at it and maybe added it to the "Popular Extenstions" section of the site docs.

Best Regards

**Comment by simonbrunel** [comment]
@maximAtanasov looks great, can you submit a PR in the [Chart.js repository](/chartjs/Chart.js) adding your extention in the *Integrations/Java* section of the [extensions.md](/chartjs/Chart.js/blob/master/docs/notes/extensions.md#java) file?

**Comment by maximAtanasov** [comment]
@simonbrunel ,
Yes, I will do that :)
